### ISSUE TITLE
view doesn't move with cursor when inserting carriagereturn or paste text

### ISSUE THREAD

**Issue by jv-barsuk** [byhestia/springseed#106]
When the cursor is at the end of the page or the visible scroll area and i insert some carriereturn or paste some text, the view doesn't scroll to the actual cursor position. So I don't see what i just entered. 
When using the down arrow key the scrolling works fine.

**Comment by nitishch** [comment]
@zackp30  @michealharker Regarding the problem with paste, why is line 26 in `app/controllers/editors.coffee`,

    "paste #contentwrite > .inner": "paste"

put? I think because of this line, after the paste command, the cursor goes to the start of the pasted text and changes the viewport. If I comment this line out, paste works perfectly fine.
